# Site settings
title: Don Mowry
description: > # this means to ignore newlines until "baseurl:"
  Just a man who wants to know pretty much everything
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.donmowry.com" # the base hostname & protocol for your site
twitter_username: donmowry
github_username:  donmowry

# Build settings
markdown: kramdown
