# Site settings
title: A Book about Me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.donmowry.com" # the base hostname & protocol for your site
twitter_username: donmowry
github_username:  donmowry
description: "© Don Mowry"

# Build settings
markdown: kramdown
permalink: /:title
